import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase'
import { requireAuth } from '@/lib/api-auth'
import { extractForwardedSender, looksHumanName } from '@/lib/email-utils'
import { parseFhIntegrationEmail } from '@/lib/fh-integration-parser'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

/**
 * One-shot backfill: upgrade customers whose name is still the email local-part
 * (auto-generated by sync when the envelope had no display name).
 *
 * Strategy: for each affected customer, scan their last 30 inbound interactions
 * for a forwarded "From: Display Name <email>" line matching their primary email.
 * If the extracted display name looks human, write it to customers.name.
 *
 * POST (no body) → { ok, updated, scanned, skipped }
 */
export async function POST(req: NextRequest) {
  const denied = requireAuth(req)
  if (denied) return denied

  const supabase = createServiceClient()

  // Find candidates: customers whose name == their primary email local-part
  const { data: candidates, error: candErr } = await supabase
    .from('customers')
    .select('id, name, customer_identifiers(type, value, is_primary)')
    .limit(2000)

  if (candErr) {
    return NextResponse.json({ ok: false, error: candErr.message }, { status: 500 })
  }

  type Identifier = { type: string; value: string; is_primary: boolean }
  type Cust = { id: string; name: string; customer_identifiers: Identifier[] }

  const targets: Array<{ id: string; email: string; localPart: string }> = []
  for (const c of (candidates ?? []) as Cust[]) {
    const emails = (c.customer_identifiers ?? []).filter((i) => i.type === 'email')
    const primary = emails.find((i) => i.is_primary) ?? emails[0]
    if (!primary?.value || !c.name) continue
    const localPart = primary.value.toLowerCase().trim().split('@')[0]
    if (!localPart) continue
    if (c.name.toLowerCase() !== localPart) continue
    targets.push({ id: c.id, email: primary.value.toLowerCase().trim(), localPart })
  }

  let updated = 0
  let scanned = 0
  let skipped = 0

  for (const t of targets) {
    scanned++
    const { data: interactions } = await supabase
      .from('interactions')
      .select('content, subject')
      .eq('customer_id', t.id)
      .eq('type', 'email')
      .not('content', 'is', null)
      .order('occurred_at', { ascending: false })
      .limit(30)

    let bestName: string | null = null
    for (const i of interactions ?? []) {
      const body = (i.content as string) ?? ''

      // Strategy 1: FareHarbor form body has "Name: ..." line + matching email
      const fh = parseFhIntegrationEmail(body)
      if (fh.name && fh.email && fh.email.toLowerCase() === t.email && looksHumanName(fh.name)) {
        bestName = fh.name
        break
      }

      // Strategy 2: forwarded "From: Display Name <email>" matching the customer's email
      const fwd = extractForwardedSender(body)
      if (fwd && fwd.email.toLowerCase() === t.email && looksHumanName(fwd.name)) {
        bestName = fwd.name
        break // newest match wins
      }
    }

    if (!bestName) { skipped++; continue }
    const { error: updErr } = await supabase
      .from('customers')
      .update({ name: bestName })
      .eq('id', t.id)
    if (updErr) { skipped++; continue }
    updated++
  }

  return NextResponse.json({ ok: true, updated, scanned, skipped, candidates: targets.length })
}
