-- ============================================================
-- 2026-05-12 — Customer name backfill (FH-derived)
-- One-shot data update: where a customer's name is exactly the
-- email local-part (auto-generated by sync) AND we have a richer
-- FH-parsed name in an interaction, upgrade the customer name.
--
-- Safe to re-run — the WHERE clause stops matching once names
-- have been upgraded.
-- ============================================================

update customers c
set name = (i.metadata->'fh_parsed'->>'name'),
    updated_at = now()
from interactions i
join customer_identifiers ci
  on ci.customer_id = c.id
 and ci.type = 'email'
where i.customer_id = c.id
  and i.metadata->'fh_parsed'->>'name' is not null
  and length(trim(i.metadata->'fh_parsed'->>'name')) > 0
  and (
    i.metadata->'fh_parsed'->>'name' ~ '\s'
    or i.metadata->'fh_parsed'->>'name' ~ '[A-Z]'
  )
  and lower(c.name) = split_part(lower(ci.value), '@', 1)
  and length(c.name) > 0;
